### ISSUE TITLE
DDNS Updater: Record does no exist

### ISSUE THREAD

**Issue by jjosephliu** [K0p1-Git/cloudflare-ddns-updater#29]
Hello, like most of the poeple visiting this repo, I am also from NetworkChuck 😅

I've followed all the steps from the video but I am having trouble updaitng my domains.
I also am terribly sleep deprived so I apologize in advance.
I am also a complete noob to networking and linux in general so I also apologize for that
For obvious reasons I have substitued my personal information

Here's what I have down in my `cloudflare.sh`

```
auth_email="myemail@myemail" 
auth_method="global"
auth_key="****"
zone_identifier="****"
record_name="speed.mydomain.com"
ttl="3600" 
proxy=true
```

And here's what I have on cloudflare

![HLEP](https://user-images.githubusercontent.com/49181542/144932552-48b5f24b-231b-40be-a32f-9b037043d656.png)

But then when I run it I get this error: 

```
root@UbuntuPiServer0:~/cloudflare-ddns-updater# ./cloudflare.sh
<13>Dec  6 22:26:01 ubuntu: DDNS Updater: Record does not exist, perhaps create one first? (myip) for speed.mydomain.com)
root@UbuntuPiServer0:~/cloudflare-ddns-updater#
```

but when change 
`record_name="speed.mydomain.com"`
in
 `cloudflare.sh`
to
`record_name="mydomain.com"`
it works perfectly fine

I don't know if it has anthing to do with an SRV record I added earlier:
![yert](https://user-images.githubusercontent.com/49181542/144934438-36c6cd30-0c87-4ee3-a0ad-e670be9d2277.png)

Really sorry if I did/said any really stupid stuff! I'm kind of a beginner.
Feel free to correct/guide me.

Thank you!

imgoingtosleepnow

**Comment by Sailboat265** [comment]
Welcome and hi there! If I understood your issue correctly, don't worry, you're not doing anything wrong.

For this post, we will use the following shortcut. `let root = "mydomain.com"` and `let subdomain = "speed.mydomain.com"`.

Now, since you mentioned that the script works when updating your **root** but not for the **subdomain**.

This isn't a problem. This script has been coded to deal specifically on DNS with **A** Record, anything else other than it will not work. Hence, that's why the script returned an error. Because your **subdomain** is having a **SRV** record DNS.

Sooo, since your **subdomain** is just pointing back to your **root**.
You can just use the script to update your **root** content, which you already did, and it will work fine.

**Comment by jjosephliu** [comment]
Ohhh I see so, if I wanted my root to be different from my subdomain, I can't do that with an SRV record, it has to be an `A record`.

Is there any way to keep them different or a way to update SRV record? or is that not a thing.

Thanks for being so welcoming and helpfful!

**Comment by Sailboat265** [comment]
Hmmm, not gonna lie, I'm not sure about it either and I have never used SRV records.

As [here](https://www.cloudflare.com/learning/dns/dns-records/dns-srv-record/), it seems that you can't put numeric address directly as the SRV record's target as it only accepts hostname, huh. 

I also modified the script to try to update the target of a SRV record. But the changes are not being accepted by Cloudflare, it seems that SRV records are **read-only** when interacting through developer API.

So, I don't think it's possible to update SRV record directly through the Cloudflare API.

But anyways! If you want to keep SRV record and root different from each other. There's a way! Well, I think you probably knew how to do this but I'm going to leave this here anyways.

Steps:
1. Add an **A record** like **"play.mydomain.com"**, and remember set **proxy to false**.

          | Type | Name              | Content | Proxy Status | TTL  |
          |------|-------------------|---------|--------------|------|
          | A    | play.mydomain.com | your-ip | DNS only     | Auto |

2. Add an **SRV record**, for example...

         | Type | Name | Service    | Protocol | TTL  | Priority | Weight | Port  | Target            |
         |------|------|------------|----------|------|----------|--------|-------|-------------------|
         | SRV  | play | _minecraft | TCP      | Auto | 10       | 10     | 42069 | play.mydomain.com |

3. Use the script to update the **"play.mydomain.com"** record automatically.
4. BOOM! It should work fine... maybe.

PS: I can't guarantee it will work though, I can't help to verify this since I don't host a minecraft server.

Also, you're always welcome, and it's my pleasure to help you.

**Comment by jjosephliu** [comment]
Man if I could kiss you right now I would, thanks so much! It worked!

**Comment by jjosephliu** [comment]
WAIT WHAT ABOUT ABOUT A CNAME RECORD.
Is there a way similar to what you described, to update a CNAME record.
Or is there another script similar to this one that updates CNAME records.

Thanks again :)

**Comment by Sailboat265** [comment]
Glad to hear that it worked.

>Wait what about a CNAME record

Hang on, you want to update a CNAME record? Afaik, a CNAME record always point to another hostname rather than an IP.
Similar to the steps above, if you need to update a CNAME.

1. Suppose you have an **A** Record like

             | Type | Name              | Content | Proxy Status | TTL  |
             |------|-------------------|---------|--------------|------|
             | A    | play.mydomain.com | your-ip | DNS only     | Auto |

2. Just point your **CNAME** record to it like

             | Type  | Name               | Target            | Proxy Status | TTL  |
             |-------|--------------------|-------------------|--------------|------|
             | CNAME | hello.mydomain.com | play.mydomain.com | DNS only     | Auto |
3. Same step, use the script to auto update the **A Record**
4. Whenever the **A Record** IP changes, your subdomain _(hello.mydomain.com)_ will get updated indirectly because it's an alias of the target. You never have to care about the subdomain again.

I'm not a network expert, but isn't it more convenient to get things updated this way?

**Comment by jjosephliu** [comment]
### SHORT VERSION:
I am really stupid.
Instead of CNAME I can just use A record.
Becaue the only reason I need it is to act as ddns
Used CNAME because guy with beard and coffe on internet told me to

### IM REALLY STUPID VERSION
Wow ok took me a while.
Turns out the sleep deprivation really got to me.

So I did what you said, and I realized I am kind of  _really_ stupid.

### **Here's why:**
The whole reason I needed a seperate thing to update my second domain {Say hello.mydomain.com) was because I needed it to act as an unproxied ddns so that I can use it to connect my stuff.

The only reason I used a CNAME record was because **NetworkChuck** told me to :|

Then I realized I can just use an A record and leave it on DNS only instead of having to do all that {I SUPER appreciate it though!}

Man I really appreciate all the support!

If I ever find a way to give you a kiss through the internet, you'll be the first to know.
