### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Andrew-H2O** [K0p1-Git/cloudflare-ddns-updater#53]
I'm just getting started with Cloudflare.  
I have two DNS 'A' records set up in the Cloudflare dashboard - one for my root domain and a wildcard record for the subdomains.
Will your script work for this setup?
Would I have to run it twice, once for each record?  And if so, will it handle the wildcard record correctly?

**Comment by psycho-neon** [comment]
If they fall over the same domain, what you can do is to just update 1 "A" record (preferably the main domain) then use CNAME for the wildcard and point to the "A" record. This way only 1 record you need to update frequently.

**Comment by Wizman87** [comment]
To add on to K0p1-Git's comment above, if you're utilizing the same IP address for the wildcard sub-domains as you are for your root domain, then you can simply update the root domain's A record with one script and utilize your running web service (i.e. nginx/apache) to redirect to the desired sub-domain or root domain depending on what domain is requested by a useragent. In addition to psycho-neon's comment, utilizing a CNAME for the wildcard sub-domains pointing to the root domain would also work, though would require running two scripts instead of one. In the future, multi-domains may be supported, though is not currently at this time.
