### ISSUE TITLE
Can't use 2 record names at the same time.

### ISSUE THREAD

**Issue by XDark187** [K0p1-Git/cloudflare-ddns-updater#69]
Can't use 2 record names at the same time.
do I need to make 2 scripts to update 2 record names on cf?

**Comment by Sailboat265** [comment]
Hi there. Yup, you'll have to make individual scripts for each A record that you wish to update.

This is by design, as K0p1-Git (owner of this repo) stated that he intended this script is to be easily used and lightweight. And I totally agree with him! Simplicity is sometimes a better solution to a complex question.

Btw, I think it's worth mentioning that someone, has made a customized version of this script that has the said function of updating multiple record names at the same time.

[Over here!](https://github.com/timetoexpire/cloudflare-ddns-updater). But keep in mind, the project hasn't been updated in more than a year. And you'll be probably on your own if any issues came up.

**Comment by OlavAlexanderMjelde** [comment]
You can also consider using cnames if it suits you, e.g.:
Type: CNAME, name: foobar, target: domain.tld
